"""
providers/gcp/storage/vertex_vector_search.py
Vertex AI Vector Search — AbstractVectorStore implementation.

Uses the google-cloud-aiplatform SDK to upsert to a Vertex AI Matching Engine
(Vector Search) index and query via the deployed index endpoint.
Embeddings generated by Vertex AI text-embedding-005 or sentence-transformers.
"""
from __future__ import annotations

import json
from typing import Any

from google.cloud import aiplatform
from google.cloud.aiplatform.matching_engine.matching_engine_index_endpoint import (
    MatchNeighbor,
)

from core.interfaces.vector_store import AbstractVectorStore, VectorSearchResult
from providers.gcp.config.settings import get_gcp_settings


class VertexVectorSearch(AbstractVectorStore):
    """
    AbstractVectorStore backed by Vertex AI Vector Search (Matching Engine).
    Streaming upserts go to the index; queries hit the deployed endpoint.
    """

    def __init__(self) -> None:
        s = get_gcp_settings()
        aiplatform.init(project=s.gcp_project_id, location=s.gcp_region)
        self._settings = s
        self._endpoint = aiplatform.MatchingEngineIndexEndpoint(
            index_endpoint_name=s.vertex_index_endpoint_id
        )
        self._embedder = self._build_embedder(s)

    @staticmethod
    def _build_embedder(s):
        try:
            from vertexai.language_models import TextEmbeddingModel
            import vertexai
            vertexai.init(project=s.gcp_project_id, location=s.gcp_region)
            model = TextEmbeddingModel.from_pretrained(s.vertex_embedding_model)

            def embed(texts: list[str]) -> list[list[float]]:
                embeddings = model.get_embeddings(texts)
                return [e.values for e in embeddings]

            return embed
        except Exception:
            from sentence_transformers import SentenceTransformer
            local_model = SentenceTransformer("all-MiniLM-L6-v2")
            return lambda texts: local_model.encode(texts, normalize_embeddings=True).tolist()

    def upsert_chunks(self, chunks: list) -> None:
        texts = [c.content for c in chunks]
        embeddings = self._embedder(texts)
        datapoints = [
            {
                "datapoint_id": chunk.id,
                "feature_vector": emb,
                "restricts": [{"namespace": "document_id", "allow_list": [chunk.document_id]}],
            }
            for chunk, emb in zip(chunks, embeddings)
        ]
        index = aiplatform.MatchingEngineIndex(
            index_name=self._settings.vertex_index_id
        )
        index.upsert_datapoints(datapoints=datapoints)

    def search(
        self,
        query: str,
        top_k: int = 5,
        filter_by: dict[str, Any] | None = None,
    ) -> list[VectorSearchResult]:
        query_emb = self._embedder([query])[0]

        restricts = self._build_restricts(filter_by)

        neighbors = self._endpoint.find_neighbors(
            deployed_index_id=self._settings.vertex_deployed_index_id,
            queries=[query_emb],
            num_neighbors=top_k,
            filter=restricts,
        )

        results: list[VectorSearchResult] = []
        for neighbor in (neighbors[0] if neighbors else []):
            results.append(VectorSearchResult(
                chunk_id=neighbor.id,
                document_id="",   # Retrieve from metadata store in production
                content="",       # Retrieve from GCS using chunk_id as key
                score=neighbor.distance,
            ))
        return results

    @staticmethod
    def _build_restricts(filter_by: dict[str, Any] | None) -> list[dict] | None:
        if not filter_by:
            return None

        restricts = []
        for key, value in filter_by.items():
            values = value if isinstance(value, (list, tuple, set)) else [value]
            restricts.append({"namespace": key, "allow_list": [str(v) for v in values]})
        return restricts

    def delete_by_document(self, document_id: str) -> None:
        index = aiplatform.MatchingEngineIndex(index_name=self._settings.vertex_index_id)
        index.remove_datapoints(datapoint_ids=[document_id])
