"""
providers/aws/storage/opensearch_store.py
Amazon OpenSearch Service vector store — AbstractVectorStore implementation.

Uses the opensearch-py SDK with k-NN plugin for approximate nearest-neighbour search.
Embeddings generated by Amazon Titan Embed or sentence-transformers as fallback.
"""
from __future__ import annotations

import json
from typing import Any

import boto3
from opensearchpy import OpenSearch, RequestsHttpConnection
from requests_aws4auth import AWS4Auth

from core.interfaces.vector_store import AbstractVectorStore, VectorSearchResult
from providers.aws.config.settings import get_aws_settings


class OpenSearchVectorStore(AbstractVectorStore):
    """
    AbstractVectorStore backed by Amazon OpenSearch Service with k-NN index.
    Supports SigV4 request signing for IAM-based access.
    """

    VECTOR_DIM = 1536

    def __init__(self, index_name: str | None = None) -> None:
        s = get_aws_settings()
        self._index = index_name or s.opensearch_index

        # Parse host from endpoint URL
        host = s.opensearch_endpoint.replace("https://", "").rstrip("/")

        session = boto3.Session(region_name=s.aws_region)
        credentials = session.get_credentials()
        auth = AWS4Auth(
            credentials.access_key,
            credentials.secret_key,
            s.aws_region,
            "es",
            session_token=credentials.token,
        )

        self._client = OpenSearch(
            hosts=[{"host": host, "port": 443}],
            http_auth=auth,
            use_ssl=True,
            verify_certs=True,
            connection_class=RequestsHttpConnection,
        )
        self._embedder = self._build_embedder(s)
        self._ensure_index()

    @staticmethod
    def _build_filters(filter_by: dict[str, Any] | None) -> list[dict]:
        filters: list[dict] = []
        for key, value in (filter_by or {}).items():
            if isinstance(value, (list, tuple, set)):
                filters.append({"terms": {key: list(value)}})
            else:
                filters.append({"term": {key: value}})
        return filters

    @staticmethod
    def _build_embedder(s):
        try:
            bedrock = boto3.client("bedrock-runtime", region_name=s.aws_region)

            def embed(texts: list[str]) -> list[list[float]]:
                results = []
                for text in texts:
                    body = json.dumps({"inputText": text})
                    resp = bedrock.invoke_model(
                        modelId=s.bedrock_embedding_model_id,
                        body=body,
                        contentType="application/json",
                        accept="application/json",
                    )
                    results.append(json.loads(resp["body"].read())["embedding"])
                return results

            return embed
        except Exception:
            from sentence_transformers import SentenceTransformer
            model = SentenceTransformer("all-MiniLM-L6-v2")
            return lambda texts: model.encode(texts, normalize_embeddings=True).tolist()

    def _ensure_index(self) -> None:
        if self._client.indices.exists(index=self._index):
            return
        self._client.indices.create(
            index=self._index,
            body={
                "settings": {"index": {"knn": True}},
                "mappings": {
                    "properties": {
                        "id": {"type": "keyword"},
                        "document_id": {"type": "keyword"},
                        "content": {"type": "text"},
                        "embedding": {
                            "type": "knn_vector",
                            "dimension": self.VECTOR_DIM,
                            "method": {"name": "hnsw", "space_type": "cosinesimil",
                                       "engine": "nmslib"},
                        },
                    }
                },
            },
        )

    def upsert_chunks(self, chunks: list) -> None:
        texts = [c.content for c in chunks]
        embeddings = self._embedder(texts)
        for chunk, emb in zip(chunks, embeddings):
            self._client.index(
                index=self._index,
                id=chunk.id,
                body={"id": chunk.id, "document_id": chunk.document_id,
                      "content": chunk.content, "embedding": emb},
                refresh=True,
            )

    def search(
        self,
        query: str,
        top_k: int = 5,
        filter_by: dict[str, Any] | None = None,
    ) -> list[VectorSearchResult]:
        query_emb = self._embedder([query])[0]
        knn_query: dict = {
            "knn": {"embedding": {"vector": query_emb, "k": top_k}}
        }
        filters = self._build_filters(filter_by)
        if filters:
            knn_query = {"bool": {"must": [knn_query], "filter": filters}}
        resp = self._client.search(index=self._index, body={"query": knn_query, "size": top_k})
        return [
            VectorSearchResult(
                chunk_id=hit["_source"]["id"],
                document_id=hit["_source"].get("document_id", ""),
                content=hit["_source"].get("content", ""),
                score=hit["_score"],
            )
            for hit in resp["hits"]["hits"]
        ]

    def search_hybrid(
        self,
        query: str,
        top_k: int = 5,
        filter_by: dict[str, Any] | None = None,
    ) -> list[VectorSearchResult]:
        """Run BM25 keyword retrieval together with k-NN vector retrieval."""
        query_emb = self._embedder([query])[0]
        filters = self._build_filters(filter_by)
        body = {
            "query": {
                "bool": {
                    "should": [
                        {"match": {"content": {"query": query, "boost": 1.0}}},
                        {"knn": {"embedding": {"vector": query_emb, "k": top_k, "boost": 1.5}}},
                    ],
                    "minimum_should_match": 1,
                    "filter": filters,
                }
            },
            "size": top_k,
        }
        resp = self._client.search(index=self._index, body=body)
        return [
            VectorSearchResult(
                chunk_id=hit["_source"]["id"],
                document_id=hit["_source"].get("document_id", ""),
                content=hit["_source"].get("content", ""),
                score=hit["_score"],
            )
            for hit in resp["hits"]["hits"]
        ]

    def delete_by_document(self, document_id: str) -> None:
        self._client.delete_by_query(
            index=self._index,
            body={"query": {"term": {"document_id": document_id}}},
        )
